### PR TITLE
Implement more librtlsdr API

### PR DESCRIPTION
**Pull request by evanmayer**
I have implemented some functions that I found necessary. It looks like from your README.md we're keeping up with [librtlsdr/librtlsdr](https://github.com/librtlsdr/librtlsdr) as the canonical library, but it's worth mentioning that that's the library I tested against.

Disabling dithering for the R820T/2 is useful for phase coherent applications, and the GPIO pin getters/setters can be used to trigger an external RF switch to implement a Dicke radiometer, or used to interact with other hardware.

While I have tested the functions manually (e.g. verified with a multimeter that GPIO pins are flipping), I'm not sure what's expected for pytests, and the automated tests seem to fail. Posting this as draft to get feedback on the type of testing you'd like to see before PR approval.

### CODE REVIEW

**Comment by nocarryr** [comment]
Thanks!  Looks like the additions follow the existing code base and methodology.

Since I've never really gotten into the GPIO side of things on the hardware side, I'll have to defer to your knowledge.  As far as the tests go, they're failing right now because the test suite needs updating (Python 3.5 and 3.6 are EOL).

Since most of this deals with the hardware side there's really not a whole lot to be done as far as automated tests are concerned.  There's a librtlsdr [mockup](https://github.com/pyrtlsdr/pyrtlsdr/blob/7a854dcf5a1c30d0e29014ae9f24e3b35a7af859/tests/testlibrtlsdr.py#L22-L164), to simulate things, but I don't think it's necessary to add every function call to it (unless you're obsessed with code coverage).

I'll ping back here after fixing the test setup

**Comment by nocarryr** [comment]
@evanmayer the tests have been fixed.  Can you [merge](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/working-with-forks/syncing-a-fork) them in to trigger another build?

**Comment by evanmayer** [comment]
Merging and testing now!

**Comment by evanmayer** [comment]
Ping! Are the test actions operational?

**Comment by nocarryr** [comment]
> Ping! Are the test actions operational?

@evanmayer  Tests are hanging on `RtlSdrTcpServer.__init__` due to ordering with the new argument (see comment above regarding `__init__` stuff).

The `dithering_enabled` argument should be placed after existing arguments to `RtlSdr.__init__()` and `RtlSdr.open()` to preserve backwards compatibility.

**Comment by evanmayer** [comment]
I'm waiting for the Actions to run, but I think I have fixed this by placing my new kwarg last in `RtlSdr.__init__` and `RtlSdr.open`, so that it no longer interferes with the `RtlSdr` initialization in `RtlSdrTcpServer.__init__` or the `RtlSdrTcpServer.open` method. I have also exposed it to the `RtlSdr` of an `RtlSdrTcpServer` instance as well, via a pass through in `RtlSdrTcpServer.__init__`. Have I done that right?

> (see comment above regarding `__init__` stuff).

Unfortunately, I don't see any comments above regarding `__init__` stuff. Can you point it out to me or reiterate?

**Comment by nocarryr** [comment]
@evanmayer looks good, except I'm limited in my ability to test with actual hardware so I'm relying on your own verification of things.

It would be good to add generic tests for the methods added though just for good measure.  They could be added to this section of the test suite:
https://github.com/pyrtlsdr/pyrtlsdr/blob/f12444fc9fbc1dd79c0aa6a3bf3292665c518a9b/tests/utils.py#L98-L115

**_BUT_** 

Those tests would fail when running against the TCP module and I've been thinking about deprecating that nasty thing anyway.  So maybe we'll just take the hit on code coverage  🤷

The only thing remaining is the request above regarding triple quotes at the end of the docstrings (moving the closing quotes to their own line)

**Review by nocarryr — APPROVED** [review]

**Comment by nocarryr** [comment]
Whoops! I just now realized why you weren't seeing any of my comments.  I didn't click the submit button for the code review.  Still getting used to how that works, sorry about that!

**Comment by evanmayer** [comment]
Holy cow! I now see all the changes you've been talking about. This is a beef I have with the GitHub reviewing UI - you needed to click one more button after leaving all of those review comments (and it is not obvious that you need to do so). If you had checked "request changes" instead of "approve" when you finished that review, it would have sent it back to me with your comments.

I can still fix the things you've put in there. I promise I wasn't ignoring them, I just couldn't see them until just now.

**Comment by evanmayer** [comment]
One more change incoming, for the kwargs styling.

**Comment by nocarryr** [comment]
> Holy cow! I now see all the changes you've been talking about. This is a beef I have with the GitHub reviewing UI - you needed to click one more button after leaving all of those review comments (and it is not obvious that you need to do so). If you had checked "request changes" instead of "approve" when you finished that review, it would have sent it back to me with your comments.
> 
> I can still fix the things you've put in there. I promise I wasn't ignoring them, I just couldn't see them until just now.

Yeah, it was not obvious at all.  I kept looking for some way to mark things as being resolved, lol.

I think you implemented everything I suggested, aside from the __init__ method being horribly long.  I'm not too worried about that though

**Comment by nocarryr** [comment]
> One more change incoming, for the kwargs styling.

You can leave it.  There's a lot of other stuff that needs restyling anyway

**Comment by evanmayer** [comment]
> > One more change incoming, for the kwargs styling.
> 
> You can leave it. There's a lot of other stuff that needs restyling anyway

Gah, too late. Sorry! I'm hands off now, but can revert if needed. Otherwise, merge away!

**Comment by nocarryr** [comment]
LGTM, no need to trigger another build

Thanks for the contribution!  And sorry about all the confusion

**Pull request merged**
